### ISSUE TITLE
How to generate GetVideoVersionKeyScRsp.json

### ISSUE THREAD

**Issue by capric98** [BUnipendix/PyCriUsm#3]
Looks like key_gen part needs to be updated everytime new resources are added, just curious how do you generate these configuration file or would you update this repo at your convienience?

**Comment by BUnipendix** [comment]
captured from the kcp packet

**Comment by BUnipendix** [comment]
you just need to login even if you didn't achieve the progress.

**Comment by mqnowa** [comment]
Is it TLS communication?
Is there a way to decrypt it using Wireshark or some other tool?

**Comment by BUnipendix** [comment]
> Is it TLS communication?
> Is there a way to decrypt it using Wireshark or some other tool?

[Iridium-SR](https://github.com/tamilpp25/Iridium-SR)
use this tool

**Comment by capric98** [comment]
Thanks for your information!
