### ISSUE TITLE
You might accidently add a dot?

### ISSUE THREAD

**Issue by Gassery** [BUnipendix/PyCriUsm#4]
I was importing the demux.py, and it gives me this error message:

from .decrypt import VideoDecrypter
ImportError: attempted relative import with no known parent package

After I remove that '.' before decrypt it works fine.

To be honest, I don't know what '.decrypt' is, so this could be a result of my misuse, if this is the case, I apologize.

**Comment by BUnipendix** [comment]
maybe you put your script into cri_usm_demuxer you should treat this folder as module

**Comment by Gassery** [comment]
Cool, I think you're right.
