### ISSUE TITLE
Can someone tell me how to use it?

### ISSUE THREAD

**Issue by CuteCat233** [BUnipendix/PyCriUsm#9]
import asyncio
from pycriusm import extract_usm
videos, audios = asyncio.run(extract_usm("_Path_", "_output_folder_", is_async=True))

Error:
ImportError: dynamic module does not define module export function (PyInit_pycriusm)

Can anyone tell me how to use it?

**Comment by BUnipendix** [comment]
did you compile cython code correctly? if so, please tell me your system and hardware environment

**Comment by CuteCat233** [comment]
找到问题了
电脑安了两个Python，一个有Cython，另一个没有
编译的时候用的没有的那个
寄
